Add analytics
fs-webdev/fs-album-display pull request #51
Opened 2020-10-08 21:18 UTC by dcravenus

2020-10-08 21:34 UTC, jasonallen68 requested changes

2020-10-08 21:34 UTC, jasonallen68 commented on fs-album-slideshow.html
> +        link_name: 'Memories: Slideshow: Share'
The app name and page name are dynamically added to the link name, so you don't need to include it here.  Also, I would talk to Roger to make sure this is the link name he wants.  He's the one that will have to use it look up the analytics.

2020-10-08 21:35 UTC, dcravenus commented on fs-album-slideshow.html
> +        link_name: 'Memories: Slideshow: Share'
Yeah, he told me to do 'Memories: Slideshow: Share' or if I must, 'Memories: Album: Slideshow: Share'

2020-10-08 21:35 UTC, dcravenus commented on fs-album-slideshow.html
> +        link_name: 'Memories: Slideshow: Share'
So Memories and Slideshow are probably already included?

2020-10-08 21:36 UTC, jasonallen68 commented on fs-album-slideshow.html
> +        link_name: 'Memories: Slideshow: Share'
Not sure about  Slideshow.  The page portion of the link name comes from the .ejs page.

2020-10-09 18:46 UTC, jasonallen68 approved these changes

2020-10-09 19:46 UTC, merged